# Generated by Django 4.0 on 2021-12-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lot',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('id_lot', models.CharField(max_length=150)),
                ('nb_piece', models.IntegerField()),
                ('typologie', models.CharField(max_length=50)),
                ('prix_tva_reduit', models.FloatField()),
                ('prix_ht', models.FloatField()),
                ('prix_m_ht', models.FloatField()),
                ('prix_m_ttc', models.FloatField()),
                ('orientation', models.CharField(max_length=255)),
                ('prix_tva_normal', models.FloatField()),
                ('exterieur', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('garden', models.BooleanField()),
                ('parking', models.IntegerField()),
                ('ville', models.CharField(max_length=255)),
                ('departement', models.IntegerField()),
                ('date_fin_programme', models.CharField(max_length=255)),
                ('adresse_entiere', models.CharField(max_length=255)),
                ('date_extraction', models.DateField()),
            ],
        ),
    ]
